version: 2

models:
  - name: stg_ball_by_ball
    description: "Ball-by-ball data filtered to innings 1 & 2. One row per delivery."
    columns:
      - name: match_id
        tests: [not_null]
      - name: season
        tests: [not_null]
      - name: innings
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2]
      - name: phase
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['powerplay', 'middle', 'death']
      - name: batting_position
        tests: [not_null]
